use crate::core::layer::{MarkRenderer, RenderBackend, LineConfig, CircleConfig};
use crate::core::context::PanelContext;
use crate::chart::Chart;
use crate::Precision;
use crate::TEMP_SUFFIX;
use crate::mark::errorbar::MarkErrorBar;
use crate::error::ChartonError;

/// Implementation of `MarkRenderer` for Error Bars.
/// 
/// This renderer visualizes uncertainty intervals. It supports:
/// 1. **Explicit Encodings**: Using `y` and `y2` specified by the user.
/// 2. **Implicit Encodings**: Automatically finding statistical columns (min/max) 
///    generated by `transform_errorbar_data` if `y2` is missing.
impl MarkRenderer for Chart<MarkErrorBar> {
    fn render_marks(
        &self,
        backend: &mut dyn RenderBackend,
        context: &PanelContext,
    ) -> Result<(), ChartonError> {
        let df_source = &self.data;
        
        if df_source.df.height() == 0 { return Ok(()); }

        // --- STEP 1: RESOLVE FIELD NAMES ---
        // We need to determine which columns in the DataFrame contain the interval bounds.
        let x_enc = self.encoding.x.as_ref()
            .ok_or_else(|| ChartonError::Encoding("X-axis encoding is missing".to_string()))?;
        
        let y_field = self.encoding.y.as_ref()
            .map(|y| y.field.as_str())
            .ok_or_else(|| ChartonError::Encoding("Y-axis encoding is missing".to_string()))?;

        // Logic for Implicit vs Explicit Y2:
        // If the user provided y2, use it. Otherwise, look for auto-generated temp columns.
        let (y_min_field, y_max_field) = if let Some(y2) = &self.encoding.y2 {
            (y_field.to_string(), y2.field.clone())
        } else {
            (
                format!("{}_{}_min", TEMP_SUFFIX, y_field),
                format!("{}_{}_max", TEMP_SUFFIX, y_field),
            )
        };

        let mark_config = self.mark.as_ref()
            .ok_or_else(|| ChartonError::Mark("MarkErrorBar configuration is missing".to_string()))?;

        // --- STEP 2: POSITION NORMALIZATION ---
        // Fetch the series. Note: .column() will return an error if the temp columns 
        // haven't been generated yet (i.e., if transform_errorbar_data wasn't called).
        let x_series = df_source.column(&x_enc.field)?;
        let y_min_series = df_source.column(&y_min_field)?;
        let y_max_series = df_source.column(&y_max_field)?;

        let x_scale = context.coord.get_x_scale();
        let y_scale = context.coord.get_y_scale();

        let x_norms = x_scale.scale_type().normalize_series(x_scale, &x_series)?;
        let y_min_norms = y_scale.scale_type().normalize_series(y_scale, &y_min_series)?;
        let y_max_norms = y_scale.scale_type().normalize_series(y_scale, &y_max_series)?;

        // --- STEP 3: RENDERING LOOP ---
        let color = mark_config.color.clone();
        let width = mark_config.stroke_width as Precision;
        let cap_len = mark_config.cap_length as Precision;
        let is_flipped = context.coord.is_flipped();

        for ((x_n, y_min_n), y_max_n) in x_norms.into_iter()
            .zip(y_min_norms.into_iter())
            .zip(y_max_norms.into_iter()) 
        {
            let x_norm = x_n.unwrap_or(0.0);
            let y_min_norm = y_min_n.unwrap_or(0.0);
            let y_max_norm = y_max_n.unwrap_or(0.0);

            // Project logical units to physical pixels
            let (x_pix_start, y_min_pix) = context.transform(x_norm, y_min_norm);
            let (x_pix_end, y_max_pix) = context.transform(x_norm, y_max_norm);
            
            let x1 = x_pix_start as Precision;
            let x2 = x_pix_end as Precision;
            let y1 = y_min_pix as Precision;
            let y2 = y_max_pix as Precision;

            // 1. Draw the Main Whisker
            backend.draw_line(LineConfig {
                x1, y1, x2, y2,
                color: color.clone(),
                width,
                opacity: mark_config.opacity as Precision,
                dash: None,
            });

            // 2. Draw Caps (Perpendicular to whisker)
            if !is_flipped {
                // Standard: Horizontal Caps
                backend.draw_line(LineConfig {
                    x1: x1 - cap_len, y1, x2: x1 + cap_len, y2: y1,
                    color: color.clone(), width,
                    opacity: mark_config.opacity as Precision,
                    dash: None,
                });
                backend.draw_line(LineConfig {
                    x1: x2 - cap_len, y1: y2, x2: x2 + cap_len, y2,
                    color: color.clone(), width,
                    opacity: mark_config.opacity as Precision,
                    dash: None,
                });
            } else {
                // Flipped: Vertical Caps
                backend.draw_line(LineConfig {
                    x1, y1: y1 - cap_len, x2: x1, y2: y1 + cap_len,
                    color: color.clone(), width,
                    opacity: mark_config.opacity as Precision,
                    dash: None,
                });
                backend.draw_line(LineConfig {
                    x1: x2, y1: y2 - cap_len, x2: x2, y2: y2 + cap_len,
                    color: color.clone(), width,
                    opacity: mark_config.opacity as Precision,
                    dash: None,
                });
            }

            // 3. Draw Center Point
            if mark_config.show_center {
                let y_mean_norm = (y_min_norm + y_max_norm) / 2.0;
                let (x_mean_pix, y_mean_pix) = context.transform(x_norm, y_mean_norm);
                
                backend.draw_circle(CircleConfig {
                    x: x_mean_pix as Precision,
                    y: y_mean_pix as Precision,
                    radius: 3.0 as Precision,
                    fill: color.clone(),
                    stroke: color.clone(),
                    stroke_width: 0.0,
                    opacity: mark_config.opacity as Precision,
                });
            }
        }

        Ok(())
    }
}