use crate::error::ChartonError;
use polars::datatypes::DataType;
use polars::prelude::*;
use std::collections::HashMap;
use std::io::Cursor;

/// A bridge trait that defines how data enters Charton.
/// It allows us to support local DataFrames (0.49) and external versions (via Parquet).
pub trait IntoChartonSource {
    fn into_source(self) -> Result<DataFrameSource, ChartonError>;
}

/// A wrapper around a Polars DataFrame that provides plotting-specific functionality.
///
/// This struct serves as a data source for plotting operations, encapsulating a
/// Polars DataFrame and providing convenient methods for data access and manipulation
/// needed for visualization purposes.
///
/// # Type Parameters
///
/// None
///
/// # Fields
///
/// * `df` - The underlying Polars DataFrame containing the actual data
///
/// # Examples
///
/// ```rust,ignore
/// use polars::prelude::*;
/// use charton::data::DataFrameSource;
///
/// // Create a DataFrame
/// let df = df!("x" => &[1, 2, 3], "y" => &[4, 5, 6]).unwrap();
///
/// // Wrap it in a DataFrameSource
/// let data_source = DataFrameSource::new(&df);
/// ```
#[derive(Clone)]
pub struct DataFrameSource {
    pub(crate) df: DataFrame,
}

impl DataFrameSource {
    // Creates a new `DataFrameSource` instance from a given `DataFrame`.
    pub(crate) fn new(df: DataFrame) -> Self {
        Self { df }
    }

    /// The "Universal Port": Deserializes Parquet bytes into the library's Polars version.
    /// This is the key to cross-version compatibility.
    pub fn from_parquet_bytes(bytes: &[u8]) -> Result<Self, ChartonError> {
        let cursor = Cursor::new(bytes);
        let df = ParquetReader::new(cursor).finish()?;
        Ok(Self::new(df))
    }

    // Retrieves column data by name and returns a Series object
    pub(crate) fn column(&self, name: &str) -> Result<Series, ChartonError> {
        // 1. Get the Column object. In Polars 0.49, df.column(name) returns Result<&Column, PolarsError>
        let col = self.df.column(name)?;

        // 2. Use as_materialized_series() to ensure a Series reference is obtained.
        //    This is more robust than as_series(), as it handles internal Column structures
        //    that might not be recognized as a standard Series (e.g., single-row optimization).
        let series = col.as_materialized_series();

        // 3. Clone the Series and return it
        Ok(series.clone())
    }
}

// Support for native &DataFrame (0.49)
impl IntoChartonSource for &DataFrame {
    fn into_source(self) -> Result<DataFrameSource, ChartonError> {
        Ok(DataFrameSource::new(self.clone()))
    }
}

// Support for native &LazyFrame (0.49)
impl IntoChartonSource for &LazyFrame {
    fn into_source(self) -> Result<DataFrameSource, ChartonError> {
        // .collect() consumes the LazyFrame, so we clone the reference first
        let df = self.clone().collect()?;
        Ok(DataFrameSource::new(df))
    }
}

// Support for the Parquet bridge through array of bytes
impl IntoChartonSource for &[u8] {
    fn into_source(self) -> Result<DataFrameSource, ChartonError> {
        DataFrameSource::from_parquet_bytes(self)
    }
}

// Support for the Parquet bridge through Vec of bytes
// Note: we cannot use from_parquet_bytes here without unknown reasons
impl IntoChartonSource for &Vec<u8> {
    fn into_source(self) -> Result<DataFrameSource, ChartonError> {
        let cursor = Cursor::new(self);
        let df = ParquetReader::new(cursor).finish()?;
        Ok(DataFrameSource::new(df))
    }
}

impl IntoChartonSource for Vec<u8> {
    fn into_source(self) -> Result<DataFrameSource, ChartonError> {
        DataFrameSource::from_parquet_bytes(self.as_slice())
    }
}

// A helper function to convert numeric columns to f64
pub(crate) fn convert_numeric_types(
    df_source: DataFrameSource,
) -> Result<DataFrameSource, ChartonError> {
    let mut new_columns = Vec::new();

    for col in df_source.df.get_columns() {
        use polars::datatypes::DataType::*;
        match col.dtype() {
            UInt8 | UInt16 | UInt32 | UInt64 | Int8 | Int16 | Int32 | Int64 | Int128 | Float32
            | Float64 => {
                let casted = col.cast(&Float64)?;
                new_columns.push(casted);
            }
            _ => {
                new_columns.push(col.clone());
            }
        }
    }

    let new_df = DataFrame::new(new_columns)?;

    Ok(DataFrameSource::new(new_df))
}

/// Represents the high-level semantic category of a data column.
///
/// We use Continuous/Discrete to distinguish between data that requires
/// interpolation (gradients/linear scales) and data that requires
/// indexing (palettes/point scales).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SemanticType {
    /// Quantitative/Numeric data (e.g., 1.2, 5.5, 100.0).
    Continuous,

    /// Categorical/Qualitative data (e.g., "Apple", "Orange", true/false).
    Discrete,

    /// Time-based data (e.g., 2026-01-21).
    Temporal,
}

/// Interprets the Polars [DataType] into a [SemanticType].
pub(crate) fn interpret_semantic_type(dtype: &DataType) -> SemanticType {
    match dtype {
        // Numeric types -> Continuous
        DataType::Float32
        | DataType::Float64
        | DataType::Int32
        | DataType::Int64
        | DataType::UInt32
        | DataType::UInt64 => SemanticType::Continuous,

        // Time types -> Temporal
        DataType::Date | DataType::Datetime(_, _) | DataType::Time => SemanticType::Temporal,

        // String, Categorical, Boolean -> Discrete
        DataType::String | DataType::Categorical(_, _) | DataType::Boolean => {
            SemanticType::Discrete
        }

        // Fallback for everything else (List, Struct, Null)
        _ => SemanticType::Discrete,
    }
}

/// Validates that the DataFrame contains the required columns and that their
/// data types align with the expected semantic categories (Continuous, Discrete, Temporal).
///
/// This validation ensures that aesthetic mappings (e.g., color, size) are mathematically
/// compatible with the underlying data. For instance, a 'size' encoding typically
/// requires 'Continuous' data to map values to pixel diameters.
///
/// # Arguments
/// * `df` - The Polars DataFrame to validate.
/// * `required_columns` - A list of column names that must be present in the data.
/// * `expected_semantics` - A map linking column names to their allowed [SemanticType]s.
///
/// # Returns
/// * `Ok(())` if all requirements are met.
/// * `Err(ChartonError::Encoding)` if a column is missing.
/// * `Err(ChartonError::Data)` if a column's semantic type is incompatible.
pub(crate) fn check_schema(
    df: &mut DataFrame,
    required_columns: &[&str],
    expected_semantics: &HashMap<&str, Vec<SemanticType>>,
) -> Result<(), ChartonError> {
    let schema = df.schema();

    for &col_name in required_columns {
        // 1. Ensure the column exists in the current schema
        let actual_dtype = schema.get(col_name).ok_or_else(|| {
            ChartonError::Encoding(format!("Column '{}' not found in DataFrame", col_name))
        })?;

        // 2. Map the low-level Polars DataType to our high-level SemanticType
        let actual_semantic = interpret_semantic_type(actual_dtype);

        // 3. If semantic constraints are provided for this column, validate them
        if let Some(allowed_semantics) = expected_semantics.get(col_name)
            && !allowed_semantics.contains(&actual_semantic)
        {
            return Err(ChartonError::Data(format!(
                "Column '{}' (Type: {:?}) is categorized as {:?}, but expected one of {:?}",
                col_name, actual_dtype, actual_semantic, allowed_semantics
            )));
        }
    }

    Ok(())
}

/// Represents the statistical aggregation operations available for data transformation.
///
/// This enum defines how multiple data points are collapsed into a single value
/// during the transformation phase (e.g., in Bar or ErrorBar charts).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum AggregateOp {
    /// Total sum of all values in the group. Default for most charts.
    #[default]
    Sum,
    /// Arithmetic mean (average).
    Mean,
    /// The middle value in the sorted data set.
    Median,
    /// The smallest value in the group.
    Min,
    /// The largest value in the group.
    Max,
    /// The total count of data records in the group.
    Count,
}

impl AggregateOp {
    /// Converts the aggregation operator directly into a Polars expression.
    ///
    /// By centralizing this in `data.rs`, any component with access to the
    /// data source can consistently apply statistical summaries to a field.
    pub fn into_expr(&self, field: &str) -> Expr {
        match self {
            Self::Sum => col(field).sum(),
            Self::Mean => col(field).mean(),
            Self::Median => col(field).median(),
            Self::Min => col(field).min(),
            Self::Max => col(field).max(),
            Self::Count => col(field).count(),
        }
    }
}

/// Provides a convenient way to convert string literals into `AggregateOp`.
/// This enables the "String-based API" for end-users (e.g., .aggregate("mean")).
impl From<&str> for AggregateOp {
    fn from(s: &str) -> Self {
        match s.to_lowercase().as_str() {
            "mean" | "avg" => Self::Mean,
            "sum" => Self::Sum,
            "min" => Self::Min,
            "max" => Self::Max,
            "count" | "n" => Self::Count,
            "median" => Self::Median,
            // Fallback to default Sum for unrecognized strings
            _ => Self::Sum,
        }
    }
}

/// Load built-in datasets.
///
/// Based on the passed dataset name `dataset`, returns the corresponding `DataFrame` or an error.
///
/// # Arguments
///
/// - `dataset`: Dataset name, supporting the following options:
///   - `"mtcars"`: Motor trend car road tests dataset (32 rows × 12 columns)
///   - `"iris"`: Edgar Anderson's Iris Data (150 rows × 5 columns)
///   - `"mpg"`: Subset of first 10 rows from UCI Auto MPG dataset
///   - `"nightingale"`: Dataset for Florence Nightingale's famous polar area diagram.
///   - `"penguins"`: Detaset that includes data points across a sample size of 344 penguins (344 rows × 7 columns).
///
/// # Returns
///
/// On success, returns a `DataFrame` containing the specified dataset content;
/// on failure, returns a `ChartonError`.
///
/// # Examples
///
/// ```rust,ignore
/// let df = load_dataset("mtcars")?;
/// ```
pub fn load_dataset(dataset: &str) -> Result<DataFrame, ChartonError> {
    match dataset {
        // mtcars dataset: Classic automobile performance dataset from https://www.kaggle.com/datasets/ruiromanini/mtcars
        "mtcars" => {
            // Car model column (string type)
            let model = vec![
                "Mazda RX4",
                "Mazda RX4 Wag",
                "Datsun 710",
                "Hornet 4 Drive",
                "Hornet Sportabout",
                "Valiant",
                "Duster 360",
                "Merc 240D",
                "Merc 230",
                "Merc 280",
                "Merc 280C",
                "Merc 450SE",
                "Merc 450SL",
                "Merc 450SLC",
                "Cadillac Fleetwood",
                "Lincoln Continental",
                "Chrysler Imperial",
                "Fiat 128",
                "Honda Civic",
                "Toyota Corolla",
                "Toyota Corona",
                "Dodge Challenger",
                "AMC Javelin",
                "Camaro Z28",
                "Pontiac Firebird",
                "Fiat X1-9",
                "Porsche 914-2",
                "Lotus Europa",
                "Ford Pantera L",
                "Ferrari Dino",
                "Maserati Bora",
                "Volvo 142E",
            ];

            // Numeric variable columns (f64 type)
            let mpg: Vec<f64> = vec![
                21.0, 21.0, 22.8, 21.4, 18.7, 18.1, 14.3, 24.4, 22.8, 19.2, 17.8, 16.4, 17.3, 15.2,
                10.4, 10.4, 14.7, 32.4, 30.4, 33.9, 21.5, 15.5, 15.2, 13.3, 19.2, 27.3, 26.0, 30.4,
                15.8, 19.7, 15.0, 21.4,
            ]; // Miles per gallon

            // Integer variable columns (i32 type)
            let cyl = vec![
                6, 6, 4, 6, 8, 6, 8, 4, 4, 6, 6, 8, 8, 8, 8, 8, 8, 4, 4, 4, 4, 8, 8, 8, 8, 4, 4, 4,
                8, 6, 8, 4,
            ]; // Number of cylinders

            let disp: Vec<f64> = vec![
                160.0, 160.0, 108.0, 258.0, 360.0, 225.0, 360.0, 146.7, 140.8, 167.6, 167.6, 275.8,
                275.8, 275.8, 472.0, 460.0, 440.0, 78.7, 75.7, 71.1, 120.1, 318.0, 304.0, 350.0,
                400.0, 79.0, 120.3, 95.1, 351.0, 145.0, 301.0, 121.0,
            ]; // Displacement (cubic inches)

            let hp = vec![
                110, 110, 93, 110, 175, 105, 245, 62, 95, 123, 123, 180, 180, 180, 205, 215, 230,
                66, 52, 65, 97, 150, 150, 245, 175, 66, 91, 113, 264, 175, 335, 109,
            ]; // Horsepower

            let drat: Vec<f64> = vec![
                3.90, 3.90, 3.85, 3.08, 3.15, 2.76, 3.21, 3.69, 3.92, 3.92, 3.92, 3.07, 3.07, 3.07,
                2.93, 3.00, 3.23, 4.08, 4.93, 4.22, 3.70, 2.76, 3.15, 3.73, 3.08, 4.08, 4.43, 3.77,
                4.22, 3.62, 3.54, 4.11,
            ]; // Rear axle ratio

            let wt: Vec<f64> = vec![
                2.620, 2.875, 2.320, 3.215, 3.440, 3.460, 3.570, 3.190, 3.150, 3.440, 3.440, 4.070,
                3.730, 3.780, 5.250, 5.424, 5.345, 2.200, 1.615, 1.835, 2.465, 3.520, 3.435, 3.840,
                3.845, 1.935, 2.140, 1.513, 3.170, 2.770, 3.570, 2.780,
            ]; // Weight (1000 lbs)

            let qsec: Vec<f64> = vec![
                16.46, 17.02, 18.61, 19.44, 17.02, 20.22, 15.84, 20.00, 22.90, 18.30, 18.90, 17.40,
                17.60, 18.00, 17.98, 17.82, 17.42, 19.47, 18.52, 19.90, 20.01, 16.87, 17.30, 15.41,
                17.05, 18.90, 16.70, 16.90, 14.50, 15.50, 14.60, 18.60,
            ]; // 1/4 mile time

            let vs = vec![
                0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,
                0, 0, 0, 1,
            ]; // Engine shape (0=V-shaped, 1=straight)

            let am = vec![
                1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
                1, 1, 1, 1,
            ]; // Transmission type (0=automatic, 1=manual)

            let gear = vec![
                4, 4, 4, 3, 3, 3, 3, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 4, 4, 4, 3, 3, 3, 3, 3, 4, 5, 5,
                5, 5, 5, 4,
            ]; // Number of forward gears

            let carb = vec![
                4, 4, 1, 1, 2, 1, 4, 2, 2, 4, 4, 3, 3, 3, 4, 4, 4, 1, 2, 1, 1, 2, 2, 4, 2, 1, 2, 2,
                4, 6, 8, 2,
            ]; // Number of carburetors

            // Use df! macro to build DataFrame and handle possible errors
            let df = df!(
                "model" => model,
                "mpg" => mpg,
                "cyl" => cyl,
                "disp" => disp,
                "hp" => hp,
                "drat" => drat,
                "wt" => wt,
                "qsec" => qsec,
                "vs" => vs,
                "am" => am,
                "gear" => gear,
                "carb" => carb
            )?;

            Ok(df)
        }
        // iris dataset: Classic iris flower classification dataset from https://www.kaggle.com/datasets/uciml/iris
        "iris" => {
            // Sepal length, width; Petal length, width (all numeric)
            let sepal_length: &[f64; 150] = &[
                5.1, 4.9, 4.7, 4.6, 5.0, 5.4, 4.6, 5.0, 4.4, 4.9, 5.4, 4.8, 4.8, 4.3, 5.8, 5.7,
                5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5.0, 5.0, 5.2, 5.2, 4.7, 4.8, 5.4,
                5.2, 5.5, 4.9, 5.0, 5.5, 4.9, 4.4, 5.1, 5.0, 4.5, 4.4, 5.0, 5.1, 4.8, 5.1, 4.6,
                5.3, 5.0, 7.0, 6.4, 6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5.0, 5.9, 6.0, 6.1,
                5.6, 6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7, 6.0, 5.7,
                5.5, 5.5, 5.8, 6.0, 5.4, 6.0, 6.7, 6.3, 5.6, 5.5, 5.5, 6.1, 5.8, 5.0, 5.6, 5.7,
                5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3, 6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4,
                6.8, 5.7, 5.8, 6.4, 6.5, 7.7, 7.7, 6.0, 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1,
                6.4, 7.2, 7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6.0, 6.9, 6.7, 6.9, 5.8, 6.8,
                6.7, 6.7, 6.3, 6.5, 6.2, 5.9,
            ];

            let sepal_width: &[f64; 150] = &[
                3.5, 3.0, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3.0, 3.0, 4.0, 4.4,
                3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3.0, 3.4, 3.5, 3.4, 3.2, 3.1, 3.4,
                4.1, 4.2, 3.1, 3.2, 3.5, 3.1, 3.0, 3.4, 3.5, 2.3, 3.2, 3.5, 3.8, 3.0, 3.8, 3.2,
                3.7, 3.3, 3.2, 3.2, 3.1, 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2.0, 3.0, 2.2, 2.9,
                2.9, 3.1, 3.0, 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, 2.8, 2.9, 3.0, 2.8, 3.0, 2.9, 2.6,
                2.4, 2.4, 2.7, 2.7, 3.0, 3.4, 3.1, 2.3, 3.0, 2.5, 2.6, 3.0, 2.6, 2.3, 2.7, 3.0,
                2.9, 2.9, 2.5, 2.8, 3.3, 2.7, 3.0, 2.9, 3.0, 3.0, 2.5, 2.9, 2.5, 3.6, 3.2, 2.7,
                3.0, 2.5, 2.8, 3.2, 3.0, 3.8, 2.6, 2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2, 2.8, 3.0,
                2.8, 3.0, 2.8, 3.8, 2.8, 2.8, 2.6, 3.0, 3.4, 3.1, 3.0, 3.1, 3.1, 3.1, 2.7, 3.2,
                3.3, 3.0, 2.5, 3.0, 3.4, 3.0,
            ];

            let petal_length: &[f64; 150] = &[
                1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4, 1.1, 1.2, 1.5,
                1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1.0, 1.7, 1.9, 1.6, 1.6, 1.5, 1.4, 1.6, 1.6, 1.5,
                1.5, 1.4, 1.5, 1.2, 1.3, 1.5, 1.3, 1.5, 1.3, 1.3, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4,
                1.5, 1.4, 4.7, 4.5, 4.9, 4.0, 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4.0, 4.7,
                3.6, 4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4.0, 4.9, 4.7, 4.3, 4.4, 4.8, 5.0, 4.5, 3.5,
                3.8, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4.0, 4.4, 4.6, 4.0, 3.3, 4.2, 4.2,
                4.2, 4.3, 3.0, 4.1, 6.0, 5.1, 5.9, 5.6, 5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3,
                5.5, 5.0, 5.1, 5.3, 5.5, 6.7, 6.9, 5.0, 5.7, 4.9, 6.7, 4.9, 5.7, 6.0, 4.8, 4.9,
                5.6, 5.8, 6.1, 6.4, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 5.6, 5.1, 5.1, 5.9,
                5.7, 5.2, 5.0, 5.2, 5.4, 5.1,
            ];

            let petal_width: &[f64; 150] = &[
                0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 0.1, 0.1, 0.2, 0.4,
                0.4, 0.3, 0.3, 0.3, 0.2, 0.4, 0.2, 0.5, 0.2, 0.2, 0.4, 0.2, 0.2, 0.2, 0.2, 0.4,
                0.1, 0.2, 0.1, 0.2, 0.2, 0.1, 0.2, 0.2, 0.3, 0.3, 0.2, 0.6, 0.4, 0.3, 0.2, 0.2,
                0.2, 0.2, 1.4, 1.5, 1.5, 1.3, 1.5, 1.3, 1.6, 1.0, 1.3, 1.4, 1.0, 1.5, 1.0, 1.4,
                1.3, 1.4, 1.5, 1.0, 1.5, 1.1, 1.8, 1.3, 1.5, 1.2, 1.3, 1.4, 1.4, 1.7, 1.5, 1.0,
                1.1, 1.0, 1.2, 1.6, 1.5, 1.6, 1.5, 1.3, 1.3, 1.3, 1.2, 1.4, 1.2, 1.0, 1.3, 1.2,
                1.3, 1.3, 1.1, 1.3, 2.5, 1.9, 2.1, 1.8, 2.2, 2.1, 1.7, 1.8, 1.8, 2.5, 2.0, 1.9,
                2.1, 2.0, 2.4, 2.3, 1.8, 2.2, 2.3, 1.5, 2.3, 2.0, 2.0, 1.8, 2.1, 1.8, 1.8, 1.8,
                2.1, 1.6, 1.9, 2.0, 2.2, 1.5, 1.4, 2.3, 2.4, 1.8, 1.8, 2.1, 2.4, 2.3, 1.9, 2.3,
                2.5, 2.3, 1.9, 2.0, 2.3, 1.8,
            ];

            // Species labels (string type), 50 records per class
            let species: Vec<&str> = (0..50)
                .map(|_| "setosa")
                .chain((0..50).map(|_| "versicolor"))
                .chain((0..50).map(|_| "virginica"))
                .collect();

            // Construct and return DataFrame
            let df = df![
                "sepal_length" => sepal_length,
                "sepal_width"  => sepal_width,
                "petal_length" => petal_length,
                "petal_width"  => petal_width,
                "species"      => species,
            ]?;

            Ok(df)
        }
        // mpg dataset: A small sample (first 10 rows) from https://www.kaggle.com/datasets/uciml/autompg-dataset
        "mpg" => {
            // Build a small DataFrame with partial fields
            let df = df![
                "mpg" =>        [18, 15, 18, 16, 17, 15, 14, 14, 14, 15],
                "cylinders" =>  [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
                "displacement" => [307, 350, 318, 304, 302, 429, 454, 440, 455, 390],
                "horsepower" => [130, 165, 150, 150, 140, 198, 220, 215, 225, 190],
                "weight" =>     [3504, 3693, 3436, 3433, 3449, 4341, 4354, 4312, 4425, 3850],
                "acceleration" => [12.0, 11.5, 11.0, 12.0, 10.5, 10.0, 9.0, 8.5, 10.0, 8.5],
                "model_year" => [70, 70, 70, 70, 70, 70, 70, 70, 70, 70],
                "origin" =>     [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
                "car_name" => [
                    "chevrolet chevelle malibu",
                    "buick skylark 320",
                    "plymouth satellite",
                    "amc rebel sst",
                    "ford torino",
                    "ford galaxie 500",
                    "chevrolet impala",
                    "plymouth fury iii",
                    "pontiac catalina",
                    "amc ambassador dpl"
                ]
            ]?;

            Ok(df)
        }
        // Nightingale wind rose dataset from https://github.com/stdlib-js/datasets-nightingales-rose/blob/main/data/data.csv
        // and https://github.com/vincentarelbundock/Rdatasets/blob/master/csv/HistData/Nightingale.csv
        "nightingale" => {
            let date: &[&str; 36] = &[
                "1854-04-01T07:00:00.000Z",
                "1854-05-01T07:00:00.000Z",
                "1854-06-01T07:00:00.000Z",
                "1854-07-01T07:00:00.000Z",
                "1854-08-01T07:00:00.000Z",
                "1854-09-01T07:00:00.000Z",
                "1854-10-01T07:00:00.000Z",
                "1854-11-01T07:00:00.000Z",
                "1854-12-01T08:00:00.000Z",
                "1855-01-01T08:00:00.000Z",
                "1855-02-01T08:00:00.000Z",
                "1855-03-01T08:00:00.000Z",
                "1854-04-01T07:00:00.000Z",
                "1854-05-01T07:00:00.000Z",
                "1854-06-01T07:00:00.000Z",
                "1854-07-01T07:00:00.000Z",
                "1854-08-01T07:00:00.000Z",
                "1854-09-01T07:00:00.000Z",
                "1854-10-01T07:00:00.000Z",
                "1854-11-01T07:00:00.000Z",
                "1854-12-01T08:00:00.000Z",
                "1855-01-01T08:00:00.000Z",
                "1855-02-01T08:00:00.000Z",
                "1855-03-01T08:00:00.000Z",
                "1854-04-01T07:00:00.000Z",
                "1854-05-01T07:00:00.000Z",
                "1854-06-01T07:00:00.000Z",
                "1854-07-01T07:00:00.000Z",
                "1854-08-01T07:00:00.000Z",
                "1854-09-01T07:00:00.000Z",
                "1854-10-01T07:00:00.000Z",
                "1854-11-01T07:00:00.000Z",
                "1854-12-01T08:00:00.000Z",
                "1855-01-01T08:00:00.000Z",
                "1855-02-01T08:00:00.000Z",
                "1855-03-01T08:00:00.000Z",
            ];

            let month: &[&str; 36] = &[
                "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar",
                "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar",
                "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar",
            ];

            let year: &[&str; 36] = &[
                "1854", "1854", "1854", "1854", "1854", "1854", "1854", "1854", "1854", "1855",
                "1855", "1855", "1854", "1854", "1854", "1854", "1854", "1854", "1854", "1854",
                "1854", "1855", "1855", "1855", "1854", "1854", "1854", "1854", "1854", "1854",
                "1854", "1854", "1854", "1855", "1855", "1855",
            ];

            let army: &[u32; 36] = &[
                8571, 23333, 28333, 28722, 30246, 30290, 30643, 29736, 32779, 32393, 30919, 30107,
                8571, 23333, 28333, 28722, 30246, 30290, 30643, 29736, 32779, 32393, 30919, 30107,
                8571, 23333, 28333, 28722, 30246, 30290, 30643, 29736, 32779, 32393, 30919, 30107,
            ];

            let deaths: &[u32; 36] = &[
                0, 0, 0, 0, 1, 81, 132, 287, 114, 83, 42, 32, 5, 9, 6, 23, 30, 70, 128, 106, 131,
                324, 361, 172, 1, 12, 11, 359, 828, 788, 503, 844, 1725, 2761, 2120, 1205,
            ];

            let cause: &[&str; 36] = &[
                "Wounds", "Wounds", "Wounds", "Wounds", "Wounds", "Wounds", "Wounds", "Wounds",
                "Wounds", "Wounds", "Wounds", "Wounds", "Other", "Other", "Other", "Other",
                "Other", "Other", "Other", "Other", "Other", "Other", "Other", "Other", "Disease",
                "Disease", "Disease", "Disease", "Disease", "Disease", "Disease", "Disease",
                "Disease", "Disease", "Disease", "Disease",
            ];

            let df = df![
                "Date" => date,
                "Month" => month,
                "Year" => year,
                "Army" => army,
                "Deaths" => deaths,
                "Cause" => cause,
            ]?;

            Ok(df)
        }
        // Penguins dataset from https://www.kaggle.com/datasets/jaeyunju/penguins
        "penguins" => {
            let species: &[&str; 344] = &[
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Adelie",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Chinstrap",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
                "Gentoo",
            ];

            let island: &[&str; 344] = &[
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Torgersen",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Dream",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
                "Biscoe",
            ];

            let bill_length_mm: &[Option<f64>; 344] = &[
                Some(39.1),
                Some(39.5),
                Some(40.3),
                None,
                Some(36.7),
                Some(39.3),
                Some(38.9),
                Some(39.2),
                Some(34.1),
                Some(42.0),
                Some(37.8),
                Some(37.8),
                Some(41.1),
                Some(38.6),
                Some(34.6),
                Some(36.6),
                Some(38.7),
                Some(42.5),
                Some(34.4),
                Some(46.0),
                Some(37.8),
                Some(37.7),
                Some(35.9),
                Some(38.2),
                Some(38.8),
                Some(35.3),
                Some(40.6),
                Some(40.5),
                Some(37.9),
                Some(40.5),
                Some(39.5),
                Some(37.2),
                Some(39.5),
                Some(40.9),
                Some(36.4),
                Some(39.2),
                Some(38.8),
                Some(42.2),
                Some(37.6),
                Some(39.8),
                Some(36.5),
                Some(40.8),
                Some(36.0),
                Some(44.1),
                Some(37.0),
                Some(39.6),
                Some(41.1),
                Some(37.5),
                Some(36.0),
                Some(42.3),
                Some(39.6),
                Some(40.1),
                Some(35.0),
                Some(42.0),
                Some(34.5),
                Some(41.4),
                Some(39.0),
                Some(40.6),
                Some(36.5),
                Some(37.6),
                Some(35.7),
                Some(41.3),
                Some(37.6),
                Some(41.1),
                Some(36.4),
                Some(41.6),
                Some(35.5),
                Some(41.1),
                Some(35.9),
                Some(41.8),
                Some(33.5),
                Some(39.7),
                Some(39.6),
                Some(45.8),
                Some(35.5),
                Some(42.8),
                Some(40.9),
                Some(37.2),
                Some(36.2),
                Some(42.1),
                Some(34.6),
                Some(42.9),
                Some(36.7),
                Some(35.1),
                Some(37.3),
                Some(41.3),
                Some(36.3),
                Some(36.9),
                Some(38.3),
                Some(38.9),
                Some(35.7),
                Some(41.1),
                Some(34.0),
                Some(39.6),
                Some(36.2),
                Some(40.8),
                Some(38.1),
                Some(40.3),
                Some(33.1),
                Some(43.2),
                Some(35.0),
                Some(41.0),
                Some(37.7),
                Some(37.8),
                Some(37.9),
                Some(39.7),
                Some(38.6),
                Some(38.2),
                Some(38.1),
                Some(43.2),
                Some(38.1),
                Some(45.6),
                Some(39.7),
                Some(42.2),
                Some(39.6),
                Some(42.7),
                Some(38.6),
                Some(37.3),
                Some(35.7),
                Some(41.1),
                Some(36.2),
                Some(37.7),
                Some(40.2),
                Some(41.4),
                Some(35.2),
                Some(40.6),
                Some(38.8),
                Some(41.5),
                Some(39.0),
                Some(44.1),
                Some(38.5),
                Some(43.1),
                Some(36.8),
                Some(37.5),
                Some(38.1),
                Some(41.1),
                Some(35.6),
                Some(40.2),
                Some(37.0),
                Some(39.7),
                Some(40.2),
                Some(40.6),
                Some(32.1),
                Some(40.7),
                Some(37.3),
                Some(39.0),
                Some(39.2),
                Some(36.6),
                Some(36.0),
                Some(37.8),
                Some(36.0),
                Some(41.5),
                Some(46.5),
                Some(50.0),
                Some(51.3),
                Some(45.4),
                Some(52.7),
                Some(45.2),
                Some(46.1),
                Some(51.3),
                Some(46.0),
                Some(51.3),
                Some(46.6),
                Some(51.7),
                Some(47.0),
                Some(52.0),
                Some(45.9),
                Some(50.5),
                Some(50.3),
                Some(58.0),
                Some(46.4),
                Some(49.2),
                Some(42.4),
                Some(48.5),
                Some(43.2),
                Some(50.6),
                Some(46.7),
                Some(52.0),
                Some(50.5),
                Some(49.5),
                Some(46.4),
                Some(52.8),
                Some(40.9),
                Some(54.2),
                Some(42.5),
                Some(51.0),
                Some(49.7),
                Some(47.5),
                Some(47.6),
                Some(52.0),
                Some(46.9),
                Some(53.5),
                Some(49.0),
                Some(46.2),
                Some(50.9),
                Some(45.5),
                Some(50.9),
                Some(50.8),
                Some(50.1),
                Some(49.0),
                Some(51.5),
                Some(49.8),
                Some(48.1),
                Some(51.4),
                Some(45.7),
                Some(50.7),
                Some(42.5),
                Some(52.2),
                Some(45.2),
                Some(49.3),
                Some(50.2),
                Some(45.6),
                Some(51.9),
                Some(46.8),
                Some(45.7),
                Some(55.8),
                Some(43.5),
                Some(49.6),
                Some(50.8),
                Some(50.2),
                Some(46.1),
                Some(50.0),
                Some(48.7),
                Some(50.0),
                Some(47.6),
                Some(46.5),
                Some(45.4),
                Some(46.7),
                Some(43.3),
                Some(46.8),
                Some(40.9),
                Some(49.0),
                Some(45.5),
                Some(48.4),
                Some(45.8),
                Some(49.3),
                Some(42.0),
                Some(49.2),
                Some(46.2),
                Some(48.7),
                Some(50.2),
                Some(45.1),
                Some(46.5),
                Some(46.3),
                Some(42.9),
                Some(46.1),
                Some(44.5),
                Some(47.8),
                Some(48.2),
                Some(50.0),
                Some(47.3),
                Some(42.8),
                Some(45.1),
                Some(59.6),
                Some(49.1),
                Some(48.4),
                Some(42.6),
                Some(44.4),
                Some(44.0),
                Some(48.7),
                Some(42.7),
                Some(49.6),
                Some(45.3),
                Some(49.6),
                Some(50.5),
                Some(43.6),
                Some(45.5),
                Some(50.5),
                Some(44.9),
                Some(45.2),
                Some(46.6),
                Some(48.5),
                Some(45.1),
                Some(50.1),
                Some(46.5),
                Some(45.0),
                Some(43.8),
                Some(45.5),
                Some(43.2),
                Some(50.4),
                Some(45.3),
                Some(46.2),
                Some(45.7),
                Some(54.3),
                Some(45.8),
                Some(49.8),
                Some(46.2),
                Some(49.5),
                Some(43.5),
                Some(50.7),
                Some(47.7),
                Some(46.4),
                Some(48.2),
                Some(46.5),
                Some(46.4),
                Some(48.6),
                Some(47.5),
                Some(51.1),
                Some(45.2),
                Some(45.2),
                Some(49.1),
                Some(52.5),
                Some(47.4),
                Some(50.0),
                Some(44.9),
                Some(50.8),
                Some(43.4),
                Some(51.3),
                Some(47.5),
                Some(52.1),
                Some(47.5),
                Some(52.2),
                Some(45.5),
                Some(49.5),
                Some(44.5),
                Some(50.8),
                Some(49.4),
                Some(46.9),
                Some(48.4),
                Some(51.1),
                Some(48.5),
                Some(55.9),
                Some(47.2),
                Some(49.1),
                Some(47.3),
                Some(46.8),
                Some(41.7),
                Some(53.4),
                Some(43.3),
                Some(48.1),
                Some(50.5),
                Some(49.8),
                Some(43.5),
                Some(51.5),
                Some(46.2),
                Some(55.1),
                Some(44.5),
                Some(48.8),
                Some(47.2),
                None,
                Some(46.8),
                Some(50.4),
                Some(45.2),
                Some(49.9),
            ];

            let bill_depth_mm: &[Option<f64>; 344] = &[
                Some(18.7),
                Some(17.4),
                Some(18.0),
                None,
                Some(19.3),
                Some(20.6),
                Some(17.8),
                Some(19.6),
                Some(18.1),
                Some(20.2),
                Some(17.1),
                Some(17.3),
                Some(17.6),
                Some(21.2),
                Some(21.1),
                Some(17.8),
                Some(19.0),
                Some(20.7),
                Some(18.4),
                Some(21.5),
                Some(18.3),
                Some(18.7),
                Some(19.2),
                Some(18.1),
                Some(17.2),
                Some(18.9),
                Some(18.6),
                Some(17.9),
                Some(18.6),
                Some(18.9),
                Some(16.7),
                Some(18.1),
                Some(17.8),
                Some(18.9),
                Some(17.0),
                Some(21.1),
                Some(20.0),
                Some(18.5),
                Some(19.3),
                Some(19.1),
                Some(18.0),
                Some(18.4),
                Some(18.5),
                Some(19.7),
                Some(16.9),
                Some(18.8),
                Some(19.0),
                Some(18.9),
                Some(17.9),
                Some(21.2),
                Some(17.7),
                Some(18.9),
                Some(17.9),
                Some(19.5),
                Some(18.1),
                Some(18.6),
                Some(17.5),
                Some(18.8),
                Some(16.6),
                Some(19.1),
                Some(16.9),
                Some(21.1),
                Some(17.0),
                Some(18.2),
                Some(17.1),
                Some(18.0),
                Some(16.2),
                Some(19.1),
                Some(16.6),
                Some(19.4),
                Some(19.0),
                Some(18.4),
                Some(17.2),
                Some(18.9),
                Some(17.5),
                Some(18.5),
                Some(16.8),
                Some(19.4),
                Some(16.1),
                Some(19.1),
                Some(17.2),
                Some(17.6),
                Some(18.8),
                Some(19.4),
                Some(17.8),
                Some(20.3),
                Some(19.5),
                Some(18.6),
                Some(19.2),
                Some(18.8),
                Some(18.0),
                Some(18.1),
                Some(17.1),
                Some(18.1),
                Some(17.3),
                Some(18.9),
                Some(18.6),
                Some(18.5),
                Some(16.1),
                Some(18.5),
                Some(17.9),
                Some(20.0),
                Some(16.0),
                Some(20.0),
                Some(18.6),
                Some(18.9),
                Some(17.2),
                Some(20.0),
                Some(17.0),
                Some(19.0),
                Some(16.5),
                Some(20.3),
                Some(17.7),
                Some(19.5),
                Some(20.7),
                Some(18.3),
                Some(17.0),
                Some(20.5),
                Some(17.0),
                Some(18.6),
                Some(17.2),
                Some(19.8),
                Some(17.0),
                Some(18.5),
                Some(15.9),
                Some(19.0),
                Some(17.6),
                Some(18.3),
                Some(17.1),
                Some(18.0),
                Some(17.9),
                Some(19.2),
                Some(18.5),
                Some(18.5),
                Some(17.6),
                Some(17.5),
                Some(17.5),
                Some(20.1),
                Some(16.5),
                Some(17.9),
                Some(17.1),
                Some(17.2),
                Some(15.5),
                Some(17.0),
                Some(16.8),
                Some(18.7),
                Some(18.6),
                Some(18.4),
                Some(17.8),
                Some(18.1),
                Some(17.1),
                Some(18.5),
                Some(17.9),
                Some(19.5),
                Some(19.2),
                Some(18.7),
                Some(19.8),
                Some(17.8),
                Some(18.2),
                Some(18.2),
                Some(18.9),
                Some(19.9),
                Some(17.8),
                Some(20.3),
                Some(17.3),
                Some(18.1),
                Some(17.1),
                Some(19.6),
                Some(20.0),
                Some(17.8),
                Some(18.6),
                Some(18.2),
                Some(17.3),
                Some(17.5),
                Some(16.6),
                Some(19.4),
                Some(17.9),
                Some(19.0),
                Some(18.4),
                Some(19.0),
                Some(17.8),
                Some(20.0),
                Some(16.6),
                Some(20.8),
                Some(16.7),
                Some(18.8),
                Some(18.6),
                Some(16.8),
                Some(18.3),
                Some(20.7),
                Some(16.6),
                Some(19.9),
                Some(19.5),
                Some(17.5),
                Some(19.1),
                Some(17.0),
                Some(17.9),
                Some(18.5),
                Some(17.9),
                Some(19.6),
                Some(18.7),
                Some(17.3),
                Some(16.4),
                Some(19.0),
                Some(17.3),
                Some(19.7),
                Some(17.3),
                Some(18.8),
                Some(16.6),
                Some(19.9),
                Some(18.8),
                Some(19.4),
                Some(19.5),
                Some(16.5),
                Some(17.0),
                Some(19.8),
                Some(18.1),
                Some(18.2),
                Some(19.0),
                Some(18.7),
                Some(13.2),
                Some(16.3),
                Some(14.1),
                Some(15.2),
                Some(14.5),
                Some(13.5),
                Some(14.6),
                Some(15.3),
                Some(13.4),
                Some(15.4),
                Some(13.7),
                Some(16.1),
                Some(13.7),
                Some(14.6),
                Some(14.6),
                Some(15.7),
                Some(13.5),
                Some(15.2),
                Some(14.5),
                Some(15.1),
                Some(14.3),
                Some(14.5),
                Some(14.5),
                Some(15.8),
                Some(13.1),
                Some(15.1),
                Some(14.3),
                Some(15.0),
                Some(14.3),
                Some(15.3),
                Some(15.3),
                Some(14.2),
                Some(14.5),
                Some(17.0),
                Some(14.8),
                Some(16.3),
                Some(13.7),
                Some(17.3),
                Some(13.6),
                Some(15.7),
                Some(13.7),
                Some(16.0),
                Some(13.7),
                Some(15.0),
                Some(15.9),
                Some(13.9),
                Some(13.9),
                Some(15.9),
                Some(13.3),
                Some(15.8),
                Some(14.2),
                Some(14.1),
                Some(14.4),
                Some(15.0),
                Some(14.4),
                Some(15.4),
                Some(13.9),
                Some(15.0),
                Some(14.5),
                Some(15.3),
                Some(13.8),
                Some(14.9),
                Some(13.9),
                Some(15.7),
                Some(14.2),
                Some(16.8),
                Some(14.4),
                Some(16.2),
                Some(14.2),
                Some(15.0),
                Some(15.0),
                Some(15.6),
                Some(15.6),
                Some(14.8),
                Some(15.0),
                Some(16.0),
                Some(14.2),
                Some(16.3),
                Some(13.8),
                Some(16.4),
                Some(14.5),
                Some(15.6),
                Some(14.6),
                Some(15.9),
                Some(13.8),
                Some(17.3),
                Some(14.4),
                Some(14.2),
                Some(14.0),
                Some(17.0),
                Some(15.0),
                Some(17.1),
                Some(14.5),
                Some(16.1),
                Some(14.7),
                Some(15.7),
                Some(15.8),
                Some(14.6),
                Some(14.4),
                Some(16.5),
                Some(15.0),
                Some(17.0),
                Some(15.5),
                Some(15.0),
                Some(13.8),
                Some(16.1),
                Some(14.7),
                Some(15.8),
                Some(14.0),
                Some(15.1),
                Some(15.2),
                Some(15.9),
                Some(15.2),
                Some(16.3),
                Some(14.1),
                Some(16.0),
                Some(15.7),
                Some(16.2),
                Some(13.7),
                None,
                Some(14.3),
                Some(15.7),
                Some(14.8),
                Some(16.1),
            ];

            let flipper_length_mm: &[Option<u32>; 344] = &[
                Some(181),
                Some(186),
                Some(195),
                None,
                Some(193),
                Some(190),
                Some(181),
                Some(195),
                Some(193),
                Some(190),
                Some(186),
                Some(180),
                Some(182),
                Some(191),
                Some(198),
                Some(185),
                Some(195),
                Some(197),
                Some(184),
                Some(194),
                Some(174),
                Some(180),
                Some(189),
                Some(185),
                Some(180),
                Some(187),
                Some(183),
                Some(187),
                Some(172),
                Some(180),
                Some(178),
                Some(178),
                Some(188),
                Some(184),
                Some(195),
                Some(196),
                Some(190),
                Some(180),
                Some(181),
                Some(184),
                Some(182),
                Some(195),
                Some(186),
                Some(196),
                Some(185),
                Some(190),
                Some(182),
                Some(179),
                Some(190),
                Some(191),
                Some(186),
                Some(188),
                Some(190),
                Some(200),
                Some(187),
                Some(191),
                Some(186),
                Some(193),
                Some(181),
                Some(194),
                Some(185),
                Some(195),
                Some(185),
                Some(192),
                Some(184),
                Some(192),
                Some(195),
                Some(188),
                Some(190),
                Some(198),
                Some(190),
                Some(190),
                Some(196),
                Some(197),
                Some(190),
                Some(195),
                Some(191),
                Some(184),
                Some(187),
                Some(195),
                Some(189),
                Some(196),
                Some(187),
                Some(193),
                Some(191),
                Some(194),
                Some(190),
                Some(189),
                Some(189),
                Some(190),
                Some(202),
                Some(205),
                Some(185),
                Some(186),
                Some(187),
                Some(208),
                Some(190),
                Some(196),
                Some(178),
                Some(192),
                Some(192),
                Some(203),
                Some(183),
                Some(190),
                Some(193),
                Some(184),
                Some(199),
                Some(190),
                Some(181),
                Some(197),
                Some(198),
                Some(191),
                Some(193),
                Some(197),
                Some(191),
                Some(196),
                Some(188),
                Some(199),
                Some(189),
                Some(189),
                Some(187),
                Some(198),
                Some(176),
                Some(202),
                Some(186),
                Some(199),
                Some(191),
                Some(195),
                Some(191),
                Some(210),
                Some(190),
                Some(197),
                Some(193),
                Some(199),
                Some(187),
                Some(190),
                Some(191),
                Some(200),
                Some(185),
                Some(193),
                Some(193),
                Some(187),
                Some(188),
                Some(190),
                Some(192),
                Some(185),
                Some(190),
                Some(184),
                Some(195),
                Some(193),
                Some(187),
                Some(201),
                Some(192),
                Some(196),
                Some(193),
                Some(188),
                Some(197),
                Some(198),
                Some(178),
                Some(197),
                Some(195),
                Some(198),
                Some(193),
                Some(194),
                Some(185),
                Some(201),
                Some(190),
                Some(201),
                Some(197),
                Some(181),
                Some(190),
                Some(195),
                Some(181),
                Some(191),
                Some(187),
                Some(193),
                Some(195),
                Some(197),
                Some(200),
                Some(200),
                Some(191),
                Some(205),
                Some(187),
                Some(201),
                Some(187),
                Some(203),
                Some(195),
                Some(199),
                Some(195),
                Some(210),
                Some(192),
                Some(205),
                Some(210),
                Some(187),
                Some(196),
                Some(196),
                Some(196),
                Some(201),
                Some(190),
                Some(212),
                Some(187),
                Some(198),
                Some(199),
                Some(201),
                Some(193),
                Some(203),
                Some(187),
                Some(197),
                Some(191),
                Some(203),
                Some(202),
                Some(194),
                Some(206),
                Some(189),
                Some(195),
                Some(207),
                Some(202),
                Some(193),
                Some(210),
                Some(198),
                Some(211),
                Some(230),
                Some(210),
                Some(218),
                Some(215),
                Some(210),
                Some(211),
                Some(219),
                Some(209),
                Some(215),
                Some(214),
                Some(216),
                Some(214),
                Some(213),
                Some(210),
                Some(217),
                Some(210),
                Some(221),
                Some(209),
                Some(222),
                Some(218),
                Some(215),
                Some(213),
                Some(215),
                Some(215),
                Some(215),
                Some(216),
                Some(215),
                Some(210),
                Some(220),
                Some(222),
                Some(209),
                Some(207),
                Some(230),
                Some(220),
                Some(220),
                Some(213),
                Some(219),
                Some(208),
                Some(208),
                Some(208),
                Some(225),
                Some(210),
                Some(216),
                Some(222),
                Some(217),
                Some(210),
                Some(225),
                Some(213),
                Some(215),
                Some(210),
                Some(220),
                Some(210),
                Some(225),
                Some(217),
                Some(220),
                Some(208),
                Some(220),
                Some(208),
                Some(224),
                Some(208),
                Some(221),
                Some(214),
                Some(231),
                Some(219),
                Some(230),
                Some(214),
                Some(229),
                Some(220),
                Some(223),
                Some(216),
                Some(221),
                Some(221),
                Some(217),
                Some(216),
                Some(230),
                Some(209),
                Some(220),
                Some(215),
                Some(223),
                Some(212),
                Some(221),
                Some(212),
                Some(224),
                Some(212),
                Some(228),
                Some(218),
                Some(218),
                Some(212),
                Some(230),
                Some(218),
                Some(228),
                Some(212),
                Some(224),
                Some(214),
                Some(226),
                Some(216),
                Some(222),
                Some(203),
                Some(225),
                Some(219),
                Some(228),
                Some(215),
                Some(228),
                Some(216),
                Some(215),
                Some(210),
                Some(219),
                Some(208),
                Some(209),
                Some(216),
                Some(229),
                Some(213),
                Some(230),
                Some(217),
                Some(230),
                Some(217),
                Some(222),
                Some(214),
                None,
                Some(215),
                Some(222),
                Some(212),
                Some(213),
            ];

            let body_mass_g: &[Option<u32>; 344] = &[
                Some(3750),
                Some(3800),
                Some(3250),
                None,
                Some(3450),
                Some(3650),
                Some(3625),
                Some(4675),
                Some(3475),
                Some(4250),
                Some(3300),
                Some(3700),
                Some(3200),
                Some(3800),
                Some(4400),
                Some(3700),
                Some(3450),
                Some(4500),
                Some(3325),
                Some(4200),
                Some(3400),
                Some(3600),
                Some(3800),
                Some(3950),
                Some(3800),
                Some(3800),
                Some(3550),
                Some(3200),
                Some(3150),
                Some(3950),
                Some(3250),
                Some(3900),
                Some(3300),
                Some(3900),
                Some(3325),
                Some(4150),
                Some(3950),
                Some(3550),
                Some(3300),
                Some(4650),
                Some(3150),
                Some(3900),
                Some(3100),
                Some(4400),
                Some(3000),
                Some(4600),
                Some(3425),
                Some(2975),
                Some(3450),
                Some(4150),
                Some(3500),
                Some(4300),
                Some(3450),
                Some(4050),
                Some(2900),
                Some(3700),
                Some(3550),
                Some(3800),
                Some(2850),
                Some(3750),
                Some(3150),
                Some(4400),
                Some(3600),
                Some(4050),
                Some(2850),
                Some(3950),
                Some(3350),
                Some(4100),
                Some(3050),
                Some(4450),
                Some(3600),
                Some(3900),
                Some(3550),
                Some(4150),
                Some(3700),
                Some(4250),
                Some(3700),
                Some(3900),
                Some(3550),
                Some(4000),
                Some(3200),
                Some(4700),
                Some(3800),
                Some(4200),
                Some(3350),
                Some(3550),
                Some(3800),
                Some(3500),
                Some(3950),
                Some(3600),
                Some(3550),
                Some(4300),
                Some(3400),
                Some(4450),
                Some(3300),
                Some(4300),
                Some(3700),
                Some(4350),
                Some(2900),
                Some(4100),
                Some(3725),
                Some(4725),
                Some(3075),
                Some(4250),
                Some(2925),
                Some(3550),
                Some(3750),
                Some(3900),
                Some(3175),
                Some(4775),
                Some(3825),
                Some(4600),
                Some(3200),
                Some(4275),
                Some(3900),
                Some(4075),
                Some(2900),
                Some(3775),
                Some(3350),
                Some(3325),
                Some(3150),
                Some(3500),
                Some(3450),
                Some(3875),
                Some(3050),
                Some(4000),
                Some(3275),
                Some(4300),
                Some(3050),
                Some(4000),
                Some(3325),
                Some(3500),
                Some(3500),
                Some(4475),
                Some(3425),
                Some(3900),
                Some(3175),
                Some(3975),
                Some(3400),
                Some(4250),
                Some(3400),
                Some(3475),
                Some(3050),
                Some(3725),
                Some(3000),
                Some(3650),
                Some(4250),
                Some(3475),
                Some(3450),
                Some(3750),
                Some(3700),
                Some(4000),
                Some(3500),
                Some(3900),
                Some(3650),
                Some(3525),
                Some(3725),
                Some(3950),
                Some(3250),
                Some(3750),
                Some(4150),
                Some(3700),
                Some(3800),
                Some(3775),
                Some(3700),
                Some(4050),
                Some(3575),
                Some(4050),
                Some(3300),
                Some(3700),
                Some(3450),
                Some(4400),
                Some(3600),
                Some(3400),
                Some(2900),
                Some(3800),
                Some(3300),
                Some(4150),
                Some(3400),
                Some(3800),
                Some(3700),
                Some(4550),
                Some(3200),
                Some(4300),
                Some(3350),
                Some(4100),
                Some(3600),
                Some(3900),
                Some(3850),
                Some(4800),
                Some(2700),
                Some(4500),
                Some(3950),
                Some(3650),
                Some(3550),
                Some(3500),
                Some(3675),
                Some(4450),
                Some(3400),
                Some(4300),
                Some(3250),
                Some(3675),
                Some(3325),
                Some(3950),
                Some(3600),
                Some(4050),
                Some(3350),
                Some(3450),
                Some(3250),
                Some(4050),
                Some(3800),
                Some(3525),
                Some(3950),
                Some(3650),
                Some(3650),
                Some(4000),
                Some(3400),
                Some(3775),
                Some(4100),
                Some(3775),
                Some(4500),
                Some(5700),
                Some(4450),
                Some(5700),
                Some(5400),
                Some(4550),
                Some(4800),
                Some(5200),
                Some(4400),
                Some(5150),
                Some(4650),
                Some(5550),
                Some(4650),
                Some(5850),
                Some(4200),
                Some(5850),
                Some(4150),
                Some(6300),
                Some(4800),
                Some(5350),
                Some(5700),
                Some(5000),
                Some(4400),
                Some(5050),
                Some(5000),
                Some(5100),
                Some(4100),
                Some(5650),
                Some(4600),
                Some(5550),
                Some(5250),
                Some(4700),
                Some(5050),
                Some(6050),
                Some(5150),
                Some(5400),
                Some(4950),
                Some(5250),
                Some(4350),
                Some(5350),
                Some(3950),
                Some(5700),
                Some(4300),
                Some(4750),
                Some(5550),
                Some(4900),
                Some(4200),
                Some(5400),
                Some(5100),
                Some(5300),
                Some(4850),
                Some(5300),
                Some(4400),
                Some(5000),
                Some(4900),
                Some(5050),
                Some(4300),
                Some(5000),
                Some(4450),
                Some(5550),
                Some(4200),
                Some(5300),
                Some(4400),
                Some(5650),
                Some(4700),
                Some(5700),
                Some(4650),
                Some(5800),
                Some(4700),
                Some(5550),
                Some(4750),
                Some(5000),
                Some(5100),
                Some(5200),
                Some(4700),
                Some(5800),
                Some(4600),
                Some(6000),
                Some(4750),
                Some(5950),
                Some(4625),
                Some(5450),
                Some(4725),
                Some(5350),
                Some(4750),
                Some(5600),
                Some(4600),
                Some(5300),
                Some(4875),
                Some(5550),
                Some(4950),
                Some(5400),
                Some(4750),
                Some(5650),
                Some(4850),
                Some(5200),
                Some(4925),
                Some(4875),
                Some(4625),
                Some(5250),
                Some(4850),
                Some(5600),
                Some(4975),
                Some(5500),
                Some(4725),
                Some(5500),
                Some(4700),
                Some(5500),
                Some(4575),
                Some(5500),
                Some(5000),
                Some(5950),
                Some(4650),
                Some(5500),
                Some(4375),
                Some(5850),
                Some(4875),
                Some(6000),
                Some(4925),
                None,
                Some(4850),
                Some(5750),
                Some(5200),
                Some(5400),
            ];

            let sex: &[Option<&str>; 344] = &[
                Some("MALE"),
                Some("FEMALE"),
                Some("FEMALE"),
                None,
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                None,
                None,
                None,
                None,
                Some("FEMALE"),
                Some("MALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("MALE"),
                None,
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                None,
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                None,
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                None,
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
                None,
                Some("MALE"),
                Some("FEMALE"),
                None,
                Some("FEMALE"),
                Some("MALE"),
                Some("FEMALE"),
                Some("MALE"),
            ];

            let df = df![
                "Species" => species,
                "Island" => island,
                "Bill Length (mm)" => bill_length_mm,
                "Bill Depth (mm)" => bill_depth_mm,
                "Flipper Length (mm)" => flipper_length_mm,
                "Body Mass (g)" => body_mass_g,
                "Sex" => sex,
            ]?;

            Ok(df)
        }
        // No matching known dataset name case
        _ => Err(ChartonError::Data("Dataset not found".into())),
    }
}
